; PlatformIO Project Configuration File

[platformio]
default_envs = esp32dev_ota

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
monitor_dtr   = 0
monitor_rts   = 0

[env:esp32dev_ota]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed   = 115200
monitor_dtr     = 0
monitor_rts     = 0
upload_protocol = espota
upload_port     = 192.168.1.210
